/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        btnPrimary: "var(--btn-primary)",
        bgSecondary: "var(--bg-secondary)",
      },
      fontFamily: {
        Manrope: ["Manrope", "sans-serif"],
        Yeseva: ["Yeseva", "sans-serif"],
      },
      fontSize: {
        h1: ["42px", { lineHeight: "120%" }],
        h2: ["36px", { lineHeight: "64px" }],
        h3: ["28px", { lineHeight: "120%" }],
        h4: ["24px", { lineHeight: "120%" }],
        h5: ["20px", { lineHeight: "120%" }],
        h55: ["18px", { lineHeight: "120%" }],
        h6: ["16px", { lineHeight: "120%" }],
        h7: ["14px", { lineHeight: "120%" }],
        h8: ["12px", { lineHeight: "120%" }],
        h9: ["10px", { lineHeight: "120%" }],
        body16Bold: ["16px", { lineHeight: "120%", fontWeight: "700" }],
        body16SemiBold: ["16px", { lineHeight: "120%", fontWeight: "600" }],
        body16Medium: ["16px", { lineHeight: "120%", fontWeight: "500" }],
        body16Regular: ["16px", { lineHeight: "120%", fontWeight: "400" }],
        body16Light: ["16px", { lineHeight: "120%", fontWeight: "300" }],
        body14Bold: ["14px", { lineHeight: "120%", fontWeight: "700" }],
        body14SemiBold: ["14px", { lineHeight: "120%", fontWeight: "600" }],
        body14Medium: ["14px", { lineHeight: "120%", fontWeight: "500" }],
        body14Regular: ["14px", { lineHeight: "120%", fontWeight: "400" }],
        body14Light: ["14px", { lineHeight: "120%", fontWeight: "300" }],
        body12SemiBold: ["12px", { lineHeight: "120%", fontWeight: "600" }],
        body12Medium: ["12px", { lineHeight: "120%", fontWeight: "500" }],
        body12Regular: ["12px", { lineHeight: "120%", fontWeight: "400" }],
        body12Light: ["12px", { lineHeight: "120%", fontWeight: "300" }],
        body10Bold: ["10px", { lineHeight: "120%", fontWeight: "600" }],
        body10Medium: ["10px", { lineHeight: "120%", fontWeight: "500" }],
        body10Regular: ["10px", { lineHeight: "120%", fontWeight: "400" }],
        body10Light: ["10px", { lineHeight: "120%", fontWeight: "300" }],
      },
    },
  },
  plugins: [],
};
